---
- parameter:
    name: single_use_slave_params
    parameters:
      - string:
          name: REGION
          default: "{REGION}"
      - string:
          name: FLAVOR
          default: "{FLAVOR}"
      - string:
          name: IMAGE
          default: "{IMAGE}"
      - string:
          name: INSTANCE_NAME
          default: AUTO
          description: |
            Set instance name or "AUTO" to have it generated based on job
            name and build number. Beware the 63 char container name limit
            as container names includes the host name.

- parameter:
    name: rpc_repo_params
    parameters:
      - string:
          name: "RPC_REPO"
          default: "https://github.com/rcbops/rpc-openstack"
      - string:
          name: "RPC_BRANCH"
          default: "{RPC_BRANCH}"

- parameter:
    name: osa_ops_params
    parameters:
      - string:
          name: OSA_OPS_REPO
          default: https://github.com/openstack/openstack-ansible-ops
      - string:
          name: OSA_OPS_BRANCH
          default: master
      - string:
          name: OPENSTACK_ANSIBLE_BRANCH
          default: "{OPENSTACK_ANSIBLE_BRANCH}"
          description: Openstack Ansible branch to use in setup
      - string:
          name: DEFAULT_IMAGE
          default: "{DEFAULT_IMAGE}"
          description: Version of Ubuntu image to use for VMs (14.04.5 or 16.04.2)
      - string:
          name: DEFAULT_KERNEL
          default: "4.4.0-66"
          description: Ubuntu Kernal Version to use for VMs (4.4.0-66, 3.13.0-34, etc.)
      - bool:
          name: PARTITION_HOST
          default: true
          description: Enable partitioning of host data disk device
      - string:
          name: DATA_DISK_DEVICE
          default: "{DATA_DISK_DEVICE}"
          description: The data disk to use for VMs (if unset the largest unpartitioned device will be used)
      - string:
          name: MULTI_NODE_AIO_DIR
          default: "multi-node-aio"
          description: |
            The directory to trigger build.sh from
            Options:
              multi-node-aio
              multi-node-aio-xenial-ansible

- parameter:
    name: rpc_deploy_params
    parameters:
      - string:
          name: "DEPLOY_SWIFT"
          default: "{DEPLOY_SWIFT}"
          description: "Deploy Swift? yes/no"
      - string:
          name: "DEPLOY_CEPH"
          default: "{DEPLOY_CEPH}"
          description: "Deploy Ceph? yes/no"
      - string:
          name: "DEPLOY_ELK"
          default: "{DEPLOY_ELK}"
          description: "Deploy ELK? yes/no"
      - text:
          name: "USER_VARS"
          default: "{USER_VARS}"
          description: "OSA/RPC USER_VARS to inject for this build"
      - string:
          name: "UPGRADE_FROM_REF"
          default: "{UPGRADE_FROM_REF}"
          description: "An tag/sha/ref to upgrade from"

- parameter:
    name: rpc_gating_params
    parameters:
      - string:
          name: RPC_GATING_REPO
          default: "https://github.com/rcbops/rpc-gating"
      - string:
          name: RPC_GATING_BRANCH
          default: "master"

- parameter:
    name: tempest_params
    parameters:
      - string:
          name: "TEMPEST_TEST_SETS"
          default: "{TEMPEST_TEST_SETS}"
          description: |
            Test sets (space seperated). Test sets are defined in
            https://github.com/openstack/openstack-ansible-os_tempest/blob/master/templates/openstack_tempest_gate.sh.j2
      - string:
          name: "RUN_TEMPEST_OPTS"
          default: "{RUN_TEMPEST_OPTS}"
          description: |
            Options to pass to run_tempest.sh via openstack_tempest_gate.sh. Note that both are deprecated and will be replaced in future.
            Serial test runner format: --serial
      - string:
          name: "TESTR_OPTS"
          default: "{TESTR_OPTS}"
          description: |
            Options to pass to run_tempest.sh via openstack_tempest_gate.sh. Note that both are deprecated and will be replaced in future.
            Concurrent worker format: --concurrency 3

- parameter:
    name: kibana_selenium_params
    parameters:
      - string:
          name: "KIBANA_SELENIUM_REPO"
          default: "https://github.com/rcbops-qe/kibana-selenium.git"
      - string:
          name: "KIBANA_SELENIUM_BRANCH"
          default: "{KIBANA_SELENIUM_BRANCH}"
