---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of public cloud instances
      local_action:
          module: rax
          name: "{{ name }}"
          flavor: "{{ flavor }}"
          image: "{{ image }}"
          count: "{{ count }}"
          key_name: "{{ keyname }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 900
          auto_increment: no
      register: rax
      until: rax|success
      retries: 5
      delay: 30

    - name: Write inventory
      copy:
        content: |
          [job_nodes]
          {% for instance in rax.success %} {{instance.name}} ansible_host={{instance.accessIPv4}}{% endfor %}
        dest: '{{lookup("env", "WORKSPACE")}}/rpc-gating/playbooks/inventory/hosts'

    - name: Wait for SSH to be available on all hosts
      wait_for: port=22 host="{{ item.accessIPv4 }}"
      with_items: "{{ rax.success }}"

    - name: Wait an additional amount of time for any remaning startup tasks to finish
      pause:
        minutes: 5
